### ISSUE TITLE
(1.19.2) TabStats crashing game

### ISSUE THREAD

**Issue by Lucky-56** [Crimix/TabStats#3]
TabStats seems to crash because of the player icon

https://crashy.net/8KPHoDtMNNg6xnL9DMGo

**Comment by Crimix** [comment]
Which Minecraft and Forge version?

**Comment by Crimix** [comment]
Nevermind, I see that crashy has all the information I need.
Will fix it asap

**Comment by Crimix** [comment]
Fixed in version 1.0.4 which will soon be available on Curseforge and Modrinth
