### ISSUE TITLE
PLEASE SOMEONE MAKE THIS FOR FABRIC 1.21 

### ISSUE THREAD

**Issue by CorrupterOFWorld** [Crimix/TabStats#5]
I was searching for this kind of mod for 5 literal hours, including datapacks and everything.
I couldnt get anywhere...
This dude Crimix (you are a god) made this for forge which is unfortunate. IS THERE ANY WAY SOMEONE OR SOMETHING CAN MAKE THIS FOR FABRIC?
simple, lightweight, the displaying day hour minute playing in tab is essential for me and i need taht for my server ASAP.
for fabric couldnt find anything, beside the ugly scoreboard, then command blocking the ticks etc......
Please is there anything i can do for this mod to be updated to 1.21 and be available on fabric

**Comment by CorrupterOFWorld** [comment]
New to github feel free to close the issue, becuase this is not this mods issue, more like a demand

**Comment by Crimix** [comment]
I have not dabbled with Fabric yet. For that to happen, I would have to port my library to it, not saying it is going to happen, but also not saying it won't either.

I will close this issue as there is not really any bug or issue here. Happy you found my mod and like what it does even if it on Forge

**Comment by CorrupterOFWorld** [comment]
Understood. Still impressed by the mod. Thank you. Hope that in the future it will be done in a new mod or the existing get reworked.
